//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alex.Networking.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Alex.Networking.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///       
        ///                    &quot;0x00&quot;: &quot;spawn_entity&quot;,
        ///                    &quot;0x01&quot;: &quot;spawn_entity_experience_orb&quot;,
        ///                    &quot;0x02&quot;: &quot;spawn_entity_weather&quot;,
        ///                    &quot;0x03&quot;: &quot;spawn_entity_living&quot;,
        ///                    &quot;0x04&quot;: &quot;spawn_entity_painting&quot;,
        ///                    &quot;0x05&quot;: &quot;named_entity_spawn&quot;,
        ///                    &quot;0x06&quot;: &quot;animation&quot;,
        ///                    &quot;0x07&quot;: &quot;statistics&quot;,
        ///                    &quot;0x08&quot;: &quot;block_break_animation&quot;,
        ///                    &quot;0x09&quot;: &quot;tile_entity_data&quot;, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PlayPacketID {
            get {
                return ResourceManager.GetString("PlayPacketID", resourceCulture);
            }
        }
    }
}
