namespace Alex.Entities
{
	/*public enum EntityType
	{
		None = 0,

		DroppedItem = 64,
		ExperienceOrb = 69,

		PrimedTnt = 65,
		FallingBlock = 66,

		ThrownBottleoEnchanting = 68,
		EnderEye = 70,
		EnderCrystal = 71,
		FireworksRocket = 72,
		ShulkerBullet = 76,
		FishingRodHook = 77,
		DragonFireball = 79,
		ShotArrow = 80,
		ThrownSnowball = 81,
		ThrownEgg = 82,
		Painting = 83,
		Minecart = 84,
		GhastFireball = 85,
		ThrownSpashPotion = 86,
		ThrownEnderPerl = 87,
		LeashKnot = 88,
		WitherSkull = 89,
		Boat = 90,
		WitherSkullDangerous = 91,
		LightningBolt = 93,
		BlazeFireball = 94,
		AreaEffectCloud = 95,
		HopperMinecart = 96,
		TntMinecart = 97,
		ChestMinecart = 98,
		CommandBlockMinecart = 100,
		LingeringPotion = 101,
		LlamaSpit = 102,
		EvocationFangs = 103,

		Zombie = 32,
		Creeper = 33,
		Skeleton = 34,
		Spider = 35,
		ZombiePigman = 36,
		Slime = 37,
		Enderman = 38,
		Silverfish = 39,
		CaveSpider = 40,
		Ghast = 41,
		MagmaCube = 42,
		Blaze = 43,
		ZombieVillager = 44,
		Witch = 45,
		Stray = 46,
		Husk = 47,
		WitherSkeleton = 48,
		Guardian = 49,
		ElderGuardian = 50,
		Wither = 52,
		EnderDragon = 53,
		Shulker = 54,
		Endermite = 55,
		Vindicator = 57,
		Evoker = 104,
		Vex = 105,

		Chicken = 10,
		Cow = 11,
		Pig = 12,
		Sheep = 13,
		Wolf = 14,
		Villager = 15,
		MushroomCow = 16,
		Squid = 17,
		Rabbit = 18,
		Bat = 19,
		IronGolem = 20,
		SnowGolem = 21,
		Ocelot = 22,
		Horse = 23,
		Donkey = 24,
		Mule = 25,
		SkeletonHorse = 26,
		ZombieHorse = 27,
		PolarBear = 28,
		Llama = 29,

		Player = 63,

		Npc = 51,
		Agent = 56,
		Camera = 62,
		Chalkboard = 78
	}*/
	public enum EntityType : int
	{
		None = 0,
		Item = 1,
		XPOrb = 2,
		AreaEffectCloud = 3,
		ElderGuardian = 4,
		WitherSkeleton = 5,
		Stray = 6,
		ThrownEgg = 7,
		LeashKnot = 8,
		Painting = 9,
		Arrow = 10,
		Snowball = 11,
		Fireball = 12,
		SmallFireball,
		EnderPearl = 14,
		EyeOfEnder = 15,
		Potion,
		XPBottle,
		ItemFrame,
		WitherSkull,
		PrimedTnt,
		FallingBlock,
		FireworksRocket,
		Husk,
		SpectralArrow,
		ShulkerBullet,
		DragonFireball,
		ZombieVillager,
		SkeletonHorse,
		ZombieHorse,
		ArmorStand,
		Donkey = 31,
		Mule = 32,
		EvocationFangs,
		Evoker = 34,
		Vex = 35,
		Vindicator = 36,
		MinecartWithCommandBlock = 40,
		Boat = 41,
		Minecart = 42,
		MinecartWithChest,
		MinecartWithFurnace,
		MinecartWithTNT,
		MinecartWithHopper,
		MinecartWithSpawner,

		Human = 49,
		Creeper = 50,
		Skeleton = 51,
		Spider = 52,
		Giant = 53,
		Zombie = 54,
		Slime = 55,
		Ghast = 56,
		ZombiePigman = 57,
		Enderman = 58,
		CaveSpider = 59,
		Silverfish = 60,
		Blaze = 61,
		MagmaCube = 62,
		EnderDragon = 63,
		Wither = 64,
		Bat = 65,
		Witch = 66,
		Endermite = 67,
		Guardian = 68,
		Shulker = 69,

        Cat,
        Turtle,
        PufferFish,
        Panda,
        Fox,
        Mooshroom,
        TropicalFish,
        Trident,
        Pillager,
        Phantom,
        Ravager,
        Cod,
        Dolphin,
        Drowned,
        Salmon,
		Pig = 90,
		Sheep = 91,
		Cow = 92,
		Chicken = 93,
		Squid = 94,
		Wolf = 95,
		MushroomCow = 96,
		SnowGolem = 97,
		Ocelot = 98,
		IronGolem = 99,
		Horse = 100,
		Rabbit = 101,
		PolarBear = 102,
		Llama = 103,
		Parrot = 105,
		Villager = 120,
		Bee,
		EnderCrystal = 200,
		
		
		
		ZombieVillagerV2 =500,
		VillagerV2,
		WanderingTrader,
		ChestMinecart,
		
		LlamaSpit,
	}
}