namespace Alex.Entities
{
	public enum EntityType
	{
		None = 0,

		DroppedItem = 64,
		ExperienceOrb = 69,

		PrimedTnt = 65,
		FallingBlock = 66,

		ThrownBottleoEnchanting = 68,
		EnderEye = 70,
		EnderCrystal = 71,
		FireworksRocket = 72,
		ShulkerBullet = 76,
		FishingRodHook = 77,
		DragonFireball = 79,
		ShotArrow = 80,
		ThrownSnowball = 81,
		ThrownEgg = 82,
		Painting = 83,
		Minecart = 84,
		GhastFireball = 85,
		ThrownSpashPotion = 86,
		ThrownEnderPerl = 87,
		LeashKnot = 88,
		WitherSkull = 89,
		Boat = 90,
		WitherSkullDangerous = 91,
		LightningBolt = 93,
		BlazeFireball = 94,
		AreaEffectCloud = 95,
		HopperMinecart = 96,
		TntMinecart = 97,
		ChestMinecart = 98,
		CommandBlockMinecart = 100,
		LingeringPotion = 101,
		LlamaSpit = 102,
		EvocationFangs = 103,

		Zombie = 32,
		Creeper = 33,
		Skeleton = 34,
		Spider = 35,
		ZombiePigman = 36,
		Slime = 37,
		Enderman = 38,
		Silverfish = 39,
		CaveSpider = 40,
		Ghast = 41,
		MagmaCube = 42,
		Blaze = 43,
		ZombieVillager = 44,
		Witch = 45,
		Stray = 46,
		Husk = 47,
		WitherSkeleton = 48,
		Guardian = 49,
		ElderGuardian = 50,
		Wither = 52,
		Dragon = 53,
		Shulker = 54,
		Endermite = 55,
		Vindicator = 57,
		Evoker = 104,
		Vex = 105,

		Chicken = 10,
		Cow = 11,
		Pig = 12,
		Sheep = 13,
		Wolf = 14,
		Villager = 15,
		MushroomCow = 16,
		Squid = 17,
		Rabbit = 18,
		Bat = 19,
		IronGolem = 20,
		SnowGolem = 21,
		Ocelot = 22,
		Horse = 23,
		Donkey = 24,
		Mule = 25,
		SkeletonHorse = 26,
		ZombieHorse = 27,
		PolarBear = 28,
		Llama = 29,

		Player = 63,

		Npc = 51,
		Agent = 56,
		Camera = 62,
		Chalkboard = 78
	}
/*	public enum EntityType : int
	{
		Item = 1,
		XPOrb,
		AreaEffectCloud,
		ElderGuardian,
		WitherSkeleton,
		Stray,
		Egg,
		LeashKnot,
		Painting,
		Arrow,
		Snowball,
		Fireball,
		SmallFireball,
		EnderPearl,
		EyeOfEnder,
		Potion,
		XPBottle,
		ItemFrame,
		WitherSkull,
		PrimedTnt,
		FallingBlock,
		FireworksRocket,
		Husk,
		SpectralArrow,
		ShulkerBullet,
		DragonFireball,
		ZombieVillager,
		SkeletonHorse,
		ZombieHorse,
		ArmorStand,
		Donkey,
		Mule,
		EvocationFangs,
		Evoker,
		Vex,
		Vindicator,
		MinecartWithCommandBlock = 40,
		Boat,
		Minecart,
		MinecartWithChest,
		MinecartWithFurnace,
		MinecartWithTNT,
		MinecartWithHopper,
		MinecartWithSpawner,
		Human = 49,
		Creeper,
		Skeleton,
		Spider,
		Giant,
		Zombie,
		Slime,
		Ghast,
		ZombiePigman,
		Enderman,
		CaveSpider,
		Silverfish,
		Blaze,
		MagmaCube,
		EnderDragon,
		Wither,
		Bat,
		Witch,
		Endermite,
		Guardian,
		Shulker,
		Pig = 90,
		Sheep,
		Cow,
		Chicken,
		Squid,
		Wolf,
		Mooshroom,
		SnowGolem,
		Ocelot,
		IronGolem,
		Horse,
		Rabbit,
		PolarBear,
		Llama,
		Villager = 120,
		EnderCrystal = 200,
		ThePlayer = 255, // This one actually isn't defined on the Minecraft side.
		None = -1
	}*/
}