// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by JetBrains T4 Processor
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ResourceConverterCore.Templates
{
    using System;
    #line 11 "/home/kenny/Documents/Github/Alex/src/Tools/ResourceConverterCore/Templates/EntityTemplate.tt"
using System.Linq;
    #line default
    #line hidden
    #line 12 "/home/kenny/Documents/Github/Alex/src/Tools/ResourceConverterCore/Templates/EntityTemplate.tt"
using System.Text;
    #line default
    #line hidden
    #line 13 "/home/kenny/Documents/Github/Alex/src/Tools/ResourceConverterCore/Templates/EntityTemplate.tt"
using System.Collections.Generic;
    #line default
    #line hidden
    #line 14 "/home/kenny/Documents/Github/Alex/src/Tools/ResourceConverterCore/Templates/EntityTemplate.tt"
using Alex.ResourcePackLib.Json.Models.Entities;
    #line default
    #line hidden
    #line 15 "/home/kenny/Documents/Github/Alex/src/Tools/ResourceConverterCore/Templates/EntityTemplate.tt"
using ResourceConverterCore;
    #line default
    #line hidden
    #line 16 "/home/kenny/Documents/Github/Alex/src/Tools/ResourceConverterCore/Templates/EntityTemplate.tt"
using ResourceConverterCore.Converter;
    #line default
    #line hidden
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "/home/kenny/Documents/Github/Alex/src/Tools/ResourceConverterCore/Templates/EntityTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("JetBrains.ForTea.TextTemplating", "42.42.42.42")]
    public partial class EntityTemplate : EntityTemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            
            this.Write("\n");
            this.Write("\n");
            this.Write("\n");
            #line 18 "/home/kenny/Documents/Github/Alex/src/Tools/ResourceConverterCore/Templates/EntityTemplate.tt"


	var EntityModels = ResourceConverterContext.EntityModels;
	var CurrentModelName = ResourceConverterContext.CurrentModelName;
	var CurrentModel = ResourceConverterContext.CurrentModel;


            
            #line default
            #line hidden
            this.Write("\nusing Alex.ResourcePackLib.Json.Models.Entities;\nusing Microsoft.Xna.Framework;\n\nnamespace Alex.Entities.Models \n{\n\n\tpublic partial class ");
            
            #line 32 "/home/kenny/Documents/Github/Alex/src/Tools/ResourceConverterCore/Templates/EntityTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(CurrentModelName));
            
            #line default
            #line hidden
            this.Write("Model : EntityModel\n\t{\n\t\tpublic ");
            
            #line 34 "/home/kenny/Documents/Github/Alex/src/Tools/ResourceConverterCore/Templates/EntityTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(CurrentModelName));
            
            #line default
            #line hidden
            this.Write("Model()\n\t\t{\n\t\t\t");
            #line 36 "/home/kenny/Documents/Github/Alex/src/Tools/ResourceConverterCore/Templates/EntityTemplate.tt"

				WriteLine($"Name = \"{CurrentModel.Name}\";");
				WriteLine($"\t\t\tVisibleBoundsWidth = {CurrentModel.VisibleBoundsWidth};");
				WriteLine($"\t\t\tVisibleBoundsHeight = {CurrentModel.VisibleBoundsHeight};");
				WriteLine($"\t\t\tVisibleBoundsOffset = new Vector3({CurrentModel.VisibleBoundsOffset.X}f, {CurrentModel.VisibleBoundsOffset.Y}f, {CurrentModel.VisibleBoundsOffset.Z}f);");
				WriteLine($"\t\t\tTexturewidth = {CurrentModel.Texturewidth};");
				WriteLine($"\t\t\tTextureheight = {CurrentModel.Textureheight};");
				if (CurrentModel.Bones != null)
				{
					WriteLine($"\t\t\tBones = new EntityModelBone[{CurrentModel.Bones.Length}]");
					WriteLine("\t\t\t{");
				foreach(var bone in CurrentModel.Bones)
				{
					StringBuilder builder = new StringBuilder();
					if (bone.Cubes != null)
					{
						builder.Append($"Cubes = new EntityModelCube[{bone.Cubes.Length}]");
						builder.Append("{\r\n");
						foreach (var cube in bone.Cubes)
						{
							builder.Append(
								$"\t\t\t\t\t\tnew EntityModelCube()\r\n\t\t\t\t\t\t{{\r\n\t\t\t\t\t\t\tOrigin = new Vector3({cube.Origin.X}f,{cube.Origin.Y}f,{cube.Origin.Z}f),\r\n\t\t\t\t\t\t\tSize = new Vector3({cube.Size.X}f, {cube.Size.Y}f, {cube.Size.Z}f),\r\n\t\t\t\t\t\t\tUv = new Vector2({cube.Uv.X}f, {cube.Uv.Y}f)\r\n\t\t\t\t\t\t}},\r\n");
						}
						builder.Append("\t\t\t\t\t}");
					}
					else
					{
						builder.Append($"Cubes = new EntityModelCube[0]");
					}
					WriteLine($"\t\t\t\tnew EntityModelBone(){{ \r\n\t\t\t\t\tName = \"{bone.Name}\",\r\n\t\t\t\t\tParent = \"{bone.Parent}\",\r\n\t\t\t\t\tPivot = new Vector3({bone.Pivot.X}f,{bone.Pivot.Y}f,{bone.Pivot.Z}f),\r\n\t\t\t\t\tRotation = new Vector3({bone.Rotation.X}f,{bone.Rotation.Y}f,{bone.Rotation.Z}f),\r\n\t\t\t\t\tBindPoseRotation = new Vector3({bone.BindPoseRotation.X}f,{bone.BindPoseRotation.Y}f,{bone.BindPoseRotation.Z}f),\r\n\t\t\t\t\tNeverRender = {(bone.NeverRender ? "true" : "false")},\r\n\t\t\t\t\tMirror = {(bone.Mirror ? "true" : "false")},\r\n\t\t\t\t\tReset = {(bone.Reset ? "true" : "false")},\r\n\t\t\t\t\t{builder.ToString()}\r\n\t\t\t\t}},");
				}
				WriteLine("\t\t\t};");
				}
				else
				{
					WriteLine($"\t\t\tBones = new EntityModelBone[0];");
				}
			
            
            #line default
            #line hidden
            this.Write("\t\t}\n\n\t}\n\n}");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("JetBrains.ForTea.TextTemplating", "42.42.42.42")]
    public class EntityTemplateBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
