//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alex {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Alex.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Alex {
            get {
                object obj = ResourceManager.GetObject("Alex", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] DebugFont {
            get {
                object obj = ResourceManager.GetObject("DebugFont", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///[
        ///  {
        ///    &quot;id&quot;: 1,
        ///    &quot;internalId&quot;: 1,
        ///    &quot;name&quot;: &quot;item&quot;,
        ///    &quot;displayName&quot;: &quot;Dropped item&quot;,
        ///    &quot;type&quot;: &quot;mob&quot;,
        ///    &quot;width&quot;: 0.25,
        ///    &quot;height&quot;: 0.25,
        ///    &quot;category&quot;: &quot;Drops&quot;
        ///  },
        ///  {
        ///    &quot;id&quot;: 2,
        ///    &quot;internalId&quot;: 2,
        ///    &quot;name&quot;: &quot;xp_orb&quot;,
        ///    &quot;displayName&quot;: &quot;Experience orb&quot;,
        ///    &quot;type&quot;: &quot;mob&quot;,
        ///    &quot;width&quot;: 0.5,
        ///    &quot;height&quot;: 0.5,
        ///    &quot;category&quot;: &quot;Drops&quot;
        ///  },
        ///  {
        ///    &quot;id&quot;: 3,
        ///    &quot;internalId&quot;: 3,
        ///    &quot;name&quot;: &quot;area_effect_cloud&quot;,
        ///    &quot;displayName&quot;: &quot;Area effect cloud&quot;,
        ///    &quot;type [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Entities {
            get {
                return ResourceManager.GetString("Entities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] goodblur {
            get {
                object obj = ResourceManager.GetObject("goodblur", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] GradientBlur {
            get {
                object obj = ResourceManager.GetObject("GradientBlur", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] grey_black_gradient01 {
            get {
                object obj = ResourceManager.GetObject("grey_black_gradient01", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;minecraft:air&quot;: {
        ///		&quot;protocol_id&quot;: 0
        ///	},
        ///	&quot;minecraft:stone&quot;: {
        ///		&quot;protocol_id&quot;: 1
        ///	},
        ///	&quot;minecraft:granite&quot;: {
        ///		&quot;protocol_id&quot;: 2
        ///	},
        ///	&quot;minecraft:polished_granite&quot;: {
        ///		&quot;protocol_id&quot;: 3
        ///	},
        ///	&quot;minecraft:diorite&quot;: {
        ///		&quot;protocol_id&quot;: 4
        ///	},
        ///	&quot;minecraft:polished_diorite&quot;: {
        ///		&quot;protocol_id&quot;: 5
        ///	},
        ///	&quot;minecraft:andesite&quot;: {
        ///		&quot;protocol_id&quot;: 6
        ///	},
        ///	&quot;minecraft:polished_andesite&quot;: {
        ///		&quot;protocol_id&quot;: 7
        ///	},
        ///	&quot;minecraft:grass_block&quot;: {
        ///		&quot;protocol_id&quot;: 8
        ///	},
        ///	&quot;minecraft:dirt&quot;: {
        ///		&quot;protocol_id&quot;: 9
        ///	},
        ///	&quot;minecraft:coar [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Items {
            get {
                return ResourceManager.GetString("Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] logo {
            get {
                object obj = ResourceManager.GetObject("logo", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] logo2 {
            get {
                object obj = ResourceManager.GetObject("logo2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Minecraftia {
            get {
                object obj = ResourceManager.GetObject("Minecraftia", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;minecraft:air&quot;: {
        ///    &quot;states&quot;: [
        ///      {
        ///        &quot;id&quot;: 0,
        ///        &quot;default&quot;: true
        ///      }
        ///    ]
        ///  },
        ///  &quot;minecraft:stone&quot;: {
        ///    &quot;states&quot;: [
        ///      {
        ///        &quot;id&quot;: 1,
        ///        &quot;default&quot;: true
        ///      }
        ///    ]
        ///  },
        ///  &quot;minecraft:granite&quot;: {
        ///    &quot;states&quot;: [
        ///      {
        ///        &quot;id&quot;: 2,
        ///        &quot;default&quot;: true
        ///      }
        ///    ]
        ///  },
        ///  &quot;minecraft:polished_granite&quot;: {
        ///    &quot;states&quot;: [
        ///      {
        ///        &quot;id&quot;: 3,
        ///        &quot;default&quot;: true
        ///      }
        ///    ]
        ///  },
        ///  &quot;minecraft:diorite&quot;: {
        ///    &quot;states&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NewBlocks {
            get {
                return ResourceManager.GetString("NewBlocks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;entity&quot;: {
        ///    &quot;area_effect_cloud&quot;: {
        ///      &quot;class&quot;: &quot;abp&quot;,
        ///      &quot;display_name&quot;: &quot;Area Effect Cloud&quot;,
        ///      &quot;id&quot;: 0,
        ///      &quot;name&quot;: &quot;area_effect_cloud&quot;
        ///    },
        ///    &quot;armor_stand&quot;: {
        ///      &quot;class&quot;: &quot;aiy&quot;,
        ///      &quot;display_name&quot;: &quot;Armor Stand&quot;,
        ///      &quot;height&quot;: 1.98,
        ///      &quot;id&quot;: 1,
        ///      &quot;name&quot;: &quot;armor_stand&quot;,
        ///      &quot;width&quot;: 0.5
        ///    },
        ///    &quot;arrow&quot;: {
        ///      &quot;class&quot;: &quot;all&quot;,
        ///      &quot;display_name&quot;: &quot;Arrow&quot;,
        ///      &quot;id&quot;: 2,
        ///      &quot;name&quot;: &quot;arrow&quot;
        ///    },
        ///    &quot;bat&quot;: {
        ///      &quot;class&quot;: &quot;agl&quot;,
        ///      [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NewEntities {
            get {
                return ResourceManager.GetString("NewEntities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] no {
            get {
                object obj = ResourceManager.GetObject("no", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ProgressBar {
            get {
                object obj = ResourceManager.GetObject("ProgressBar", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///	{
        ///		&quot;runtimeID&quot;: 0,
        ///		&quot;name&quot;: &quot;minecraft:air&quot;,
        ///		&quot;id&quot;: 0,
        ///		&quot;data&quot;: 0
        ///	},
        ///	{
        ///		&quot;runtimeID&quot;: 1,
        ///		&quot;name&quot;: &quot;minecraft:stone&quot;,
        ///		&quot;id&quot;: 1,
        ///		&quot;data&quot;: 0
        ///	},
        ///	{
        ///		&quot;runtimeID&quot;: 2,
        ///		&quot;name&quot;: &quot;minecraft:stone&quot;,
        ///		&quot;id&quot;: 1,
        ///		&quot;data&quot;: 1
        ///	},
        ///	{
        ///		&quot;runtimeID&quot;: 3,
        ///		&quot;name&quot;: &quot;minecraft:stone&quot;,
        ///		&quot;id&quot;: 1,
        ///		&quot;data&quot;: 2
        ///	},
        ///	{
        ///		&quot;runtimeID&quot;: 4,
        ///		&quot;name&quot;: &quot;minecraft:stone&quot;,
        ///		&quot;id&quot;: 1,
        ///		&quot;data&quot;: 3
        ///	},
        ///	{
        ///		&quot;runtimeID&quot;: 5,
        ///		&quot;name&quot;: &quot;minecraft:stone&quot;,
        ///		&quot;id&quot;: 1,
        ///		&quot;data&quot;: 4
        ///	},
        ///	{
        ///		&quot;runtim [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string runtimeid_table {
            get {
                return ResourceManager.GetString("runtimeid_table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Splash {
            get {
                object obj = ResourceManager.GetObject("Splash", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
    }
}
