//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alex {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Alex.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static byte[] no {
            get {
                object obj = ResourceManager.GetObject("no", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] logo {
            get {
                object obj = ResourceManager.GetObject("logo", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static string runtimeid_table {
            get {
                return ResourceManager.GetString("runtimeid_table", resourceCulture);
            }
        }
        
        internal static string NewBlocks {
            get {
                return ResourceManager.GetString("NewBlocks", resourceCulture);
            }
        }
        
        internal static string NLogConfig {
            get {
                return ResourceManager.GetString("NLogConfig", resourceCulture);
            }
        }
        
        internal static string Entities {
            get {
                return ResourceManager.GetString("Entities", resourceCulture);
            }
        }
        
        internal static byte[] Alex {
            get {
                object obj = ResourceManager.GetObject("Alex", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Splash {
            get {
                object obj = ResourceManager.GetObject("Splash", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ProgressBar {
            get {
                object obj = ResourceManager.GetObject("ProgressBar", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] logo2 {
            get {
                object obj = ResourceManager.GetObject("logo2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] grey_black_gradient01 {
            get {
                object obj = ResourceManager.GetObject("grey_black_gradient01", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] goodblur {
            get {
                object obj = ResourceManager.GetObject("goodblur", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] DebugFont {
            get {
                object obj = ResourceManager.GetObject("DebugFont", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] GradientBlur {
            get {
                object obj = ResourceManager.GetObject("GradientBlur", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static string NewEntities {
            get {
                return ResourceManager.GetString("NewEntities", resourceCulture);
            }
        }
        
        internal static string Items {
            get {
                return ResourceManager.GetString("Items", resourceCulture);
            }
        }
        
        internal static string BlocksProtocol {
            get {
                return ResourceManager.GetString("BlocksProtocol", resourceCulture);
            }
        }
        
        internal static string registries {
            get {
                return ResourceManager.GetString("registries", resourceCulture);
            }
        }
        
        internal static byte[] ScrollBar {
            get {
                object obj = ResourceManager.GetObject("ScrollBar", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
