//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alex.ResourcePackLib.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Alex.ResourcePackLib.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ‰PNG
        ///
        ///        ///IHDR€€Ã&gt;aËgAMA±üa+IDATxÚígeeÕ†ÃˆŠ        ///QÄQPÑˆbL411$š¨	ßôGøÝó7ü*Æh¢HŒ        ///‰±`WÄŽ`Ã2ï\;\ç½Xî)L…™³““Óvyö³Ö³Ö½ê¾àŸøÄ¡Í~;o·û)Ø3À~Û3À~Û3À~Û3À~Û3À~Û3À~Û3À~Û3À~Û3À~Û3À~Û3À~Û3À~;w·í\°Ÿ…½Øo{Øo{Øoç!ØOÁù±=ãÏØ\tÑE›‹/¾xùÌ;ß÷po—_~ùæYÏzÖæ™Ï|ææH`¯ÎáMâï1Ày¾ÍÔß3ÀÞ
        ///ØoçêöÏþóØVÀÞxînÿýïWÅ?Œñïÿ{óŸÿügoœËDþë_ÿºúÿøÇÂÿú×¿ö~€sR—8°ØöÚ÷¼_xá…›ßþö·GWû©{úš¿¯mÏ~ö³7ûÛßöðtÜ¶ÛíæÒK/]Þ%ö‘}¤í²Ë.{z1À~ô£ÍW¾ò•Í[Þò–å¦+W\qÅò:Ÿ6œ8ÏþóOê¨˜à/ùËS›þþ÷¿o~ýë_o&gt;ó™Ï,DÿÜç&gt;· ØÇ{lc×]wÝyÇÌÃ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string unknown_pack {
            get {
                return ResourceManager.GetString("unknown_pack", resourceCulture);
            }
        }
    }
}
